name: Wine Fsync CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: bootstraps.yml
          workflow_conclusion: success
          path: /opt
      - name: Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf /opt/Bootstraps/bootstraps.tar.xz
          chmod +x build_wine.sh
          export WINE_VERSION="$(wget -q -O - "https://raw.githubusercontent.com/Kron4ek/wine-tkg/refs/heads/fsync/VERSION" | tail -c +14)"
          export EXPERIMENTAL_WOW64="true"
          WINE_BRANCH=staging-tkg-fsync ./build_wine.sh
          sha256sum *.tar.xz
      - uses: actions/upload-artifact@v4
        with:
          name: Wine Fsync
          path: ./*.tar.xz

      - name: Build release
        uses: marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303
        with:
          title: wine-builds wow64 (experimental)
          automatic_release_tag: wow64
          prerelease: false
          draft: false
          files: ./*.tar.xz
          repo_token: ${{ secrets.GITHUB_TOKEN }}
